services:
  mqtt:
    build: ./Mqtt
    env_file:
      - .env
    depends_on:
      - "mongo"
  api:
    build: ./Api
    env_file:
      - .env
    depends_on:
      - "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 80:80
  app:
    build: ./Streamlit
    env_file:
      - .env
    ports:
      - 8501:8501
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27018:27017